before_script:
  - npm install -g .
  - npm install -g alloy
  - alloy compile test/alloy --config platform=ios
  - alloy compile test/alloy --config platform=android
sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
after_success: npm run coveralls